### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by StefanSalewski** [evgenyigumnov/rust-recipes-for-beginners#1]
Oh, fine that you did not gave up after the disappointing reddit poll -- I felt a bit sad as my comments might have been not very motivating.

Your project was gone for a few days, and I did not expect to see it again, it was only some luck that I tried your link again a few days later.

May I ask which AI tools you use currently? I am using mostly the OpenAI tools, as I have a paid subscription. I am using GPT-4, GPT4 o1-mini and GPT4 o1 preview, which all behave differently. The plain GPT-4 is still best in writing good technical English, o1-mini is very fast and powerful, but sometimes a bit stupid. And o1 preview sometimes crashes for longer texts, and is a bit expensive. Only 200 requests in four weeks allowed, for $20.

I still can not understand these fools that hate AI processed content that much, even when it has best quality. I assume nearly no one will create textual content in these days without strong AI support, but they might not mention it. It would be too expensive to do all manually -- like building all our goods in tiny shops instead of in large factories with machines.  

I am currently working on chapter 14 about Option types. Will try to read one of your texts in the next weeks, if your repository remains online.

Best regards,

Dr. Stefan Salewski

**Comment by evgenyigumnov** [comment]
When I write articles, I write them in my native language and ask the AI ​​to translate them into English. Moreover, I ask to translate into 1-2 paragraphs. Otherwise, if you give the entire text in one request to the AI, it starts adding its own text. I use a different approach to writing a book. I came up with the list of chapters myself. The chapters in the list are what I worked with myself. Then I made a list of what should be in the chapter and asked the AI ​​to supplement the list of recipes in the chapter. Sometimes I learned something new from the additions from the AI. Then I asked for a separate request for each recipe from the chapter to generate an explanation and a code example. I myself compile and run the codes that the AI ​​generated for each recipe and make edits to the code and description of the recipe. Sometimes I have to advise the AI ​​which code example should be used for a recipe. I mainly use ChatGPT o1-preview. The other models are very stupid. In general, AI among people will go through the phases: denial, humility, acceptance. For example, most programmers already use AI in development environments as smart code autocomplete. And programmers who receive a salary for their work in the form of code are not embarrassed by the fact that 80% of their code was generated by AI.

**Comment by evgenyigumnov** [comment]
This book is intended for those who are new to the Rust programming language but not to programming in general. In other words, it is designed for programmers who already have experience in other languages and want to learn Rust. Overall, Rust is not the best choice as a first programming language for beginners. It's recommended to start with simpler languages like Python or TypeScript, then progress to languages such as Java or Go, and only after gaining a solid foundation, approach more complex languages like C/C++ or Rust.

**Comment by evgenyigumnov** [comment]
in general, in order to study rust, you first need to read a fundamental theoretical book about how to program in rust. and then my book will be useful with recipes for typical problems and tasks facing a programmer who has started writing production code in Rust. As you noticed, my book does not contain theoretical and conceptual things. a purely applied approach to programming in rust.

**Comment by StefanSalewski** [comment]
Hello,

I think I agree with you in most points. Learning Rust as the first language is indeed very difficult, I would not recommend to try that. I have used for some years the Nim language, which is a bit simpler than Rust and has a syntax similar to Python, and I tried to write a real beginner book for that language. That was in 2020, without AI support, I got some negative feedback about a few grammar errors, and i think that very few people actually read that book.

Your approach, starting with a text in your native language is interesting. When GPT-3.5 came out I tried it for translating German language to English and was not too happy with the results, but I assume this process works now much better. But actually we have for many computer terms no words in German, so for me writing from the beginning in (bad) English is a quite good solution.

My current strategy with GPT is typically, that I ask GPT4-mini to create a complete draft (in English) for the full chapter. Then I typically ask them to add more content that they forget, following by a lot of manual editing. For single sections I then ask the plain GPT-4 to improve the grammar (please rewrite the text in good and correct technical English). When I am done with my own edits, I might ask GPT-4 o1 preview to rewrite the full chapter again  (please rewrite the complete text and remove redundancies and verbosity). Sometimes this works good, but for longer texts it might fail.

My general feeling is, that letting GPT generate text on its own from the beginning is a good strategy, because that text is typically good, and this process is stable, while text, that I create myself, is often removed by GPT later.

Final note: You might consider removing the "for Beginner" from your book title, it might be misleading. Generally I think, we both will have a hard time find readers for our books. When there are a few hostile fools at Reddit, it makes no sense to advertise it there. Perhaps we finally have to publish at Amazon, because many people have the habit to look for books only there. I think it is not difficult to sell a book there, started by a few fake 5 star reviews. But I would not like to go that way, and I am not writing to earn money with the book. On the other hand, having a few readers would be not bad.

Best regards,

Stefan Salewski

**Comment by evgenyigumnov** [comment]
I add tagline for book title 


![IMG_3882](https://github.com/user-attachments/assets/dff289ab-5544-481e-988e-5b791113e9f8)

**Comment by evgenyigumnov** [comment]
I do not want sell this book. Reddit it is not good place for promotion )
